"""farmer_mobile_app

Revision ID: 3bf8e8cfb0ae
Revises: c5ae7917cb97
Create Date: 2026-09-21 11:32:02.796244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf8e8cfb0ae'
down_revision: Union[str, None] = 'c5ae7917cb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_documents',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('avatar', 'aadhaar', 'passbook', 'land', name='document_type', native_enum=False), nullable=False),
    sa.Column('object_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_farmer_documents_farmer_type', 'farmer_documents', ['farmer_id', 'document_type'], unique=False)
    op.create_table('fcm_device_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_index(op.f('ix_fcm_device_tokens_user_id'), 'fcm_device_tokens', ['user_id'], unique=False)
    op.add_column('crops', sa.Column('crop_name', sa.String(length=100), nullable=True))
    op.add_column('crops', sa.Column('stage', sa.Enum('Sowing', 'Growing', 'Maturity', 'Harvest', name='crop_stage', native_enum=False), server_default='Sowing', nullable=False))
    op.add_column('farm_visits', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('farm_visits', sa.Column('image_path', sa.Text(), nullable=True))
    op.add_column('farm_visits', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('farm_visits', sa.Column('recommendation', sa.Text(), nullable=True))
    op.alter_column('farm_visits', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('scheduled', 'pending_review', 'completed', 'cancelled', name='visit_status', native_enum=False),
               existing_nullable=False)
    op.add_column('farmer_profiles', sa.Column('farm_name', sa.String(length=100), nullable=True))
    op.add_column('farmer_profiles', sa.Column('village', sa.String(length=100), nullable=True))
    op.add_column('farmer_profiles', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('farmer_profiles', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('grain_sales', sa.Column('offered_price_per_kg', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('grain_sales', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('market_rates', sa.Column('variety', sa.String(length=100), nullable=True))
    op.add_column('seed_purchases', sa.Column('grade', sa.String(length=10), nullable=True))
    op.add_column('seeds', sa.Column('crop_type', sa.String(length=50), nullable=True))
    op.add_column('seeds', sa.Column('on_hold_kg', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('seeds', sa.Column('old_price', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('seeds', sa.Column('warehouse_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_seeds_crop_type'), 'seeds', ['crop_type'], unique=False)
    op.create_foreign_key('fk_seeds_warehouse_id_warehouses', 'seeds', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.add_column('warehouse_slots', sa.Column('max_bookings', sa.Integer(), server_default='10', nullable=False))
    op.add_column('warehouse_slots', sa.Column('current_booking_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('warehouses', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('warehouses', sa.Column('contact_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'contact_number')
    op.drop_column('warehouses', 'location')
    op.drop_column('warehouse_slots', 'current_booking_count')
    op.drop_column('warehouse_slots', 'max_bookings')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_seeds_warehouse_id_warehouses', 'seeds', type_='foreignkey')
    op.drop_index(op.f('ix_seeds_crop_type'), table_name='seeds')
    op.drop_column('seeds', 'warehouse_id')
    op.drop_column('seeds', 'old_price')
    op.drop_column('seeds', 'on_hold_kg')
    op.drop_column('seeds', 'crop_type')
    op.drop_column('seed_purchases', 'grade')
    op.drop_column('market_rates', 'variety')
    op.drop_column('grain_sales', 'notes')
    op.drop_column('grain_sales', 'offered_price_per_kg')
    op.drop_column('farmer_profiles', 'state')
    op.drop_column('farmer_profiles', 'district')
    op.drop_column('farmer_profiles', 'village')
    op.drop_column('farmer_profiles', 'farm_name')
    op.alter_column('farm_visits', 'status',
               existing_type=sa.Enum('scheduled', 'pending_review', 'completed', 'cancelled', name='visit_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('farm_visits', 'recommendation')
    op.drop_column('farm_visits', 'diagnosis')
    op.drop_column('farm_visits', 'image_path')
    op.drop_column('farm_visits', 'notes')
    op.drop_column('crops', 'stage')
    op.drop_column('crops', 'crop_name')
    op.drop_index(op.f('ix_fcm_device_tokens_user_id'), table_name='fcm_device_tokens')
    op.drop_table('fcm_device_tokens')
    op.drop_index('ix_farmer_documents_farmer_type', table_name='farmer_documents')
    op.drop_table('farmer_documents')
    # ### end Alembic commands ###
