"""initial schema

Revision ID: 53cb50d44f37
Revises: 
Create Date: 2026-09-19 04:24:09.206557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53cb50d44f37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeds',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'manager', 'super_admin', name='user_role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'rejected', 'suspended', name='user_status', native_enum=False), nullable=False),
    sa.Column('first_login', sa.Boolean(), nullable=False),
    sa.Column('legacy_app_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('legacy_app_user_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_change_requests',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='bank_request_status', native_enum=False), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_change_requests_farmer_id'), 'bank_change_requests', ['farmer_id'], unique=False)
    op.create_table('crops',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(length=80), nullable=False),
    sa.Column('acres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('growing', 'harvested', 'failed', 'sold', name='crop_status', native_enum=False), nullable=False),
    sa.Column('current_month', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_farmer_id'), 'crops', ['farmer_id'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('acres_of_land', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('crop_address', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('bank_status', sa.Enum('pending', 'approved', 'rejected', name='bank_status', native_enum=False), nullable=False),
    sa.Column('profile_photo', sa.Text(), nullable=True),
    sa.Column('soil_type', sa.String(length=80), nullable=True),
    sa.Column('irrigation_type', sa.String(length=80), nullable=True),
    sa.Column('primary_crop', sa.String(length=100), nullable=True),
    sa.Column('secondary_crop', sa.String(length=100), nullable=True),
    sa.Column('aadhaar_card_url', sa.Text(), nullable=True),
    sa.Column('bank_passbook_url', sa.Text(), nullable=True),
    sa.Column('land_ownership_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('market_rates',
    sa.Column('crop_type', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='market_rate_grade', native_enum=False), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('set_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('info', 'success', 'warning', 'error', name='notification_type', native_enum=False), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_type', sa.String(length=60), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_token_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('assigned_region', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('reference_type', sa.Enum('seed_purchase', 'grain_sale', 'other', name='transaction_reference_type', native_enum=False), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=120), nullable=True),
    sa.Column('direction', sa.Enum('credit', 'debit', name='transaction_direction', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='transaction_status', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_farmer_id'), 'transactions', ['farmer_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('total_capacity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_load_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_visits',
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('visit_month', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='visit_status', native_enum=False), nullable=False),
    sa.Column('verified_acres', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('visit_month IN (1,2,3,4,5,6)', name='ck_farm_visits_visit_month'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_visits_crop_id'), 'farm_visits', ['crop_id'], unique=False)
    op.create_index(op.f('ix_farm_visits_farmer_id'), 'farm_visits', ['farmer_id'], unique=False)
    op.create_table('grain_sales',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('grain_type', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='grain_grade', native_enum=False), nullable=False),
    sa.Column('raw_material_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wastage_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('good_material_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paid', name='grain_sale_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grain_sales_farmer_id'), 'grain_sales', ['farmer_id'], unique=False)
    op.create_table('seed_purchases',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('seed_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=120), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', name='payment_status', native_enum=False), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_seed_purchases_farmer_id'), 'seed_purchases', ['farmer_id'], unique=False)
    op.create_table('seed_warehouses',
    sa.Column('seed_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_id', 'warehouse_id', name='uq_seed_warehouse')
    )
    op.create_table('warehouse_inventory',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('grain_type', sa.String(length=80), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'grain_type', name='uq_warehouse_grain')
    )
    op.create_table('warehouse_slots',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('booked_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_slots_warehouse_id'), 'warehouse_slots', ['warehouse_id'], unique=False)
    op.create_table('booking_slots',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('grain_sale_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_slot_id', sa.UUID(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('grain_type', sa.String(length=80), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='booking_status', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grain_sale_id'], ['grain_sales.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['warehouse_slot_id'], ['warehouse_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_slots_farmer_id'), 'booking_slots', ['farmer_id'], unique=False)
    op.create_table('crop_inspections',
    sa.Column('booking_slot_id', sa.UUID(), nullable=False),
    sa.Column('grain_sale_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('good_quantity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bad_quantity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_slot_id'], ['booking_slots.id'], ),
    sa.ForeignKeyConstraint(['grain_sale_id'], ['grain_sales.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_inspections_booking_slot_id'), 'crop_inspections', ['booking_slot_id'], unique=False)
    op.create_index(op.f('ix_crop_inspections_grain_sale_id'), 'crop_inspections', ['grain_sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_inspections_grain_sale_id'), table_name='crop_inspections')
    op.drop_index(op.f('ix_crop_inspections_booking_slot_id'), table_name='crop_inspections')
    op.drop_table('crop_inspections')
    op.drop_index(op.f('ix_booking_slots_farmer_id'), table_name='booking_slots')
    op.drop_table('booking_slots')
    op.drop_index(op.f('ix_warehouse_slots_warehouse_id'), table_name='warehouse_slots')
    op.drop_table('warehouse_slots')
    op.drop_table('warehouse_inventory')
    op.drop_table('seed_warehouses')
    op.drop_index(op.f('ix_seed_purchases_farmer_id'), table_name='seed_purchases')
    op.drop_table('seed_purchases')
    op.drop_index(op.f('ix_grain_sales_farmer_id'), table_name='grain_sales')
    op.drop_table('grain_sales')
    op.drop_index(op.f('ix_farm_visits_farmer_id'), table_name='farm_visits')
    op.drop_index(op.f('ix_farm_visits_crop_id'), table_name='farm_visits')
    op.drop_table('farm_visits')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_transactions_farmer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('staff_profiles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('market_rates')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_crops_farmer_id'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_bank_change_requests_farmer_id'), table_name='bank_change_requests')
    op.drop_table('bank_change_requests')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('seeds')
    # ### end Alembic commands ###
