"""crop_soft_delete

Revision ID: 79d01a1cc40b
Revises: 3bf8e8cfb0ae
Create Date: 2026-09-21 14:26:25.090193

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79d01a1cc40b'
down_revision: Union[str, None] = '3bf8e8cfb0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_crops_farmer_deleted', 'crops', ['farmer_id', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crops_farmer_deleted', table_name='crops')
    op.drop_column('crops', 'deleted_at')
    # ### end Alembic commands ###
