"""rbac_perf_and_missing_endpoints

Revision ID: c5ae7917cb97
Revises: 53cb50d44f37
Create Date: 2026-09-20 13:31:14.979851

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5ae7917cb97'
down_revision: Union[str, None] = '53cb50d44f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_bank_change_requests_farmer_status', 'bank_change_requests', ['farmer_id', 'status'], unique=False)
    op.create_index('ix_bank_change_requests_status_requested', 'bank_change_requests', ['status', 'requested_at'], unique=False)
    op.create_index('ix_booking_slots_farmer_status', 'booking_slots', ['farmer_id', 'status'], unique=False)
    op.create_index('ix_booking_slots_slot_status', 'booking_slots', ['warehouse_slot_id', 'status'], unique=False)
    op.create_index('ix_booking_slots_status_created', 'booking_slots', ['status', 'created_at'], unique=False)
    op.create_index('ix_crops_farmer_status', 'crops', ['farmer_id', 'status'], unique=False)
    op.create_index('ix_crops_status_created', 'crops', ['status', 'created_at'], unique=False)
    op.create_index('ix_farm_visits_crop_month', 'farm_visits', ['crop_id', 'visit_month'], unique=False)
    op.create_index('ix_farm_visits_farmer_status', 'farm_visits', ['farmer_id', 'status'], unique=False)
    op.create_index('ix_farm_visits_scheduled_status', 'farm_visits', ['scheduled_date', 'status'], unique=False)
    op.create_index('ix_grain_sales_farmer_status', 'grain_sales', ['farmer_id', 'status'], unique=False)
    op.create_index('ix_grain_sales_status_updated', 'grain_sales', ['status', 'updated_at'], unique=False)
    op.create_index('ix_market_rates_lookup', 'market_rates', ['crop_type', 'grade', 'effective_date'], unique=False)
    op.create_index('ix_notifications_reference', 'notifications', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'revoked'], unique=False)
    op.create_index('ix_seed_purchases_farmer_status', 'seed_purchases', ['farmer_id', 'payment_status'], unique=False)
    op.create_index('ix_seed_purchases_status_created', 'seed_purchases', ['payment_status', 'created_at'], unique=False)
    op.create_index('ix_transactions_farmer_created', 'transactions', ['farmer_id', 'created_at'], unique=False)
    op.create_index('ix_transactions_reference', 'transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_index('ix_warehouse_slots_wh_date_status', 'warehouse_slots', ['warehouse_id', 'slot_date', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_warehouse_slots_wh_date_status', table_name='warehouse_slots')
    op.drop_index('ix_users_role_status', table_name='users')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_reference', table_name='transactions')
    op.drop_index('ix_transactions_farmer_created', table_name='transactions')
    op.drop_index('ix_seed_purchases_status_created', table_name='seed_purchases')
    op.drop_index('ix_seed_purchases_farmer_status', table_name='seed_purchases')
    op.drop_index('ix_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_reference', table_name='notifications')
    op.drop_index('ix_market_rates_lookup', table_name='market_rates')
    op.drop_index('ix_grain_sales_status_updated', table_name='grain_sales')
    op.drop_index('ix_grain_sales_farmer_status', table_name='grain_sales')
    op.drop_index('ix_farm_visits_scheduled_status', table_name='farm_visits')
    op.drop_index('ix_farm_visits_farmer_status', table_name='farm_visits')
    op.drop_index('ix_farm_visits_crop_month', table_name='farm_visits')
    op.drop_index('ix_crops_status_created', table_name='crops')
    op.drop_index('ix_crops_farmer_status', table_name='crops')
    op.drop_index('ix_booking_slots_status_created', table_name='booking_slots')
    op.drop_index('ix_booking_slots_slot_status', table_name='booking_slots')
    op.drop_index('ix_booking_slots_farmer_status', table_name='booking_slots')
    op.drop_index('ix_bank_change_requests_status_requested', table_name='bank_change_requests')
    op.drop_index('ix_bank_change_requests_farmer_status', table_name='bank_change_requests')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created', table_name='audit_logs')
    # ### end Alembic commands ###
